### ISSUE TITLE
Jacob please help!

### ISSUE THREAD

**Issue by MiroslavRD** [unrealorg/Unreal-Kernel#3]
There is a bully called @Lima-X-Coding . He insulted me because i was lazy! Please block him and reply to this post ok? I created a hatebase of Lima here: @anti-lima-x-coding-club

To defeat Lima, i have programmer humor.

**Comment by jlagarespo** [comment]
Wait a minute, first of all, who are you, second of all, who is Lima, and after all that, what have I to do with any of this? Also, personally i am against hatebases, i think that if you don't like someone/you don't feel comfortable with him for any reason/he is in any way harrasing or making damage to you, creating a bullying hatebase is not the way to go. Of course I can't nor i want rule over what you do or what you don't, but if you want my opinion, you should just ignore him. If instead, you are mad with him for any reason, then you should try to talk to fix the problem, and if it doesn't get fixed, for whatever reason, then you should go back to what I said above and just ignore him. Because of all this reasons, and because I don't even know who you and Lime are, I reject the invitation to join this. Althought if you could please give me a bit more of information it'd be nice.

**Comment by MiroslavRD** [comment]
Lima is a bully. He insulted me because i was lazy to code.

Well, I can deal with your opinion on hatebases, I blocked Lima. Did you?

**Comment by jlagarespo** [comment]
What I still don't understand is what do I have to do with all this?
